version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths: 
              - node_modules
      - run:
          name: Run Tests
          command: npm test